// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: delete.sql

package db

import (
	"context"
)

const deleteList = `-- name: DeleteList :exec
DELETE FROM reading_list WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteList, id)
	return err
}

const deleteNews = `-- name: DeleteNews :exec
DELETE FROM news WHERE id = $1
`

func (q *Queries) DeleteNews(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteNews, id)
	return err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUsers(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsers, id)
	return err
}
