// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	checkoutUpdata(ctx context.Context) ([]User, error)
	createUsers(ctx context.Context) error
	deleteUsers(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
