// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	AppendList(ctx context.Context, arg AppendListParams) (ReadingList, error)
	CreateNews(ctx context.Context, arg CreateNewsParams) (News, error)
	CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error)
	DeleteList(ctx context.Context, id int32) error
	DeleteNews(ctx context.Context, id int32) error
	DeleteUsers(ctx context.Context, id int32) error
	GetTopNews(ctx context.Context) ([]News, error)
}

var _ Querier = (*Queries)(nil)
